version: '3.8'

services:
  event-management-db:
    container_name: event-management
    image: postgres:15
    environment:
      POSTGRES_DB: event_management
      POSTGRES_USER: event_admin
      POSTGRES_PASSWORD: securepass
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_HOST: 0.0.0.0
      POSTGRES_PORT: 5432
    ports:
      - "5434:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./postgres/conf/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ./postgres/conf/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U event_admin -d event_management"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: postgres -c config_file=/etc/postgresql/postgresql.conf -c hba_file=/etc/postgresql/pg_hba.conf

volumes:
  pgdata: 